/*	秀丸エディタからVisual Studioを操作するマクロ
現在のファイルをビルドしていればキャンセルする。


http://d.hatena.ne.jp/ohtorii/20110402/1301719953
https://github.com/ohtorii/visual_studio_hidemaru
*/


call Main;
endmacro($$return);


Main:
	if(0==strlen(filename)){
		message("ファイル名が空白です、まずファイル名をつけて保存してください。");
		return str(false);
	}
	
	$$mode			= "0";
	$$sync			= "0";
	$$fn 			= "\"" + filename + "\" ";
	execmacro "visual_studio_call.mac", "cmd_te_cancel", $$mode, $$sync, $$fn;
	return getresultex(-1);
